[package]
authors     = ["Xavier Lau <x@acg.box>"]
description = "Rust websocket benchmark."
edition     = "2024"
homepage    = "https://hack.ink/websocket-benchmark"
license     = "GPL-3.0"
name        = "websocket-benchmark"
readme      = "README.md"
repository  = "https://github.com/hack-ink/websocket-benchmark"
version     = "0.1.1"

[profile.ci-dev]
incremental = false
inherits    = "dev"

[profile.ci-release]
inherits = "release"
lto      = true

[dependencies]
# crates.io
color-eyre        = { version = "0.6" }
futures           = { version = "0.3" }
soketto           = { version = "0.8" }
tokio             = { version = "1.49", features = ["macros", "rt-multi-thread", "sync"] }
tokio-tungstenite = { version = "0.28" }
tokio-util        = { version = "0.7", features = ["compat"] }
tokio-websockets  = { version = "0.13", features = ["client", "fastrand", "server", "sha1_smol"] }
ws-tool           = { version = "0.11", features = ["async"] }
